spring.application.name=demoweb
server.port=8082
spring.messages.basename=messages
spring.messages.encoding=UTF-8


# === CONEXIÓN A POSTGRESQL (Aiven) ===
spring.datasource.url=jdbc:postgresql://basedatosnuevo-carlos-13c8.g.aivencloud.com:14745/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_enf3ymit78qnldV7pkk
spring.datasource.driver-class-name=org.postgresql.Driver


# === spring data JPA ===
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# === SSL para Aiven ===
spring.datasource.hikari.data-source-properties=sslmode=require